name: tesia_app
description: "Tesia - Mold Detection App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  cloud_functions: 6.0.2
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  lottie: ^3.3.1
  printing: ^5.11.0
  pdf: ^3.10.4
  path_provider: ^2.0.15
  camera: ^0.11.2
  image_picker: ^1.2.0
  shimmer: ^3.0.0
  url_launcher: ^6.2.2
  qr_flutter: ^4.1.0
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  uuid: ^4.5.1
  mobile_scanner: ^7.1.2
  firebase_storage: ^13.0.2
  google_sign_in: ^6.2.1 
  google_generative_ai: ^0.4.0
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.2.3
  hive: ^2.2.0
  hive_flutter: ^1.1.0
  share_plus: 12.0.1
  change_app_package_name: ^1.3.0



  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/logos/
    - assets/images/onboarding/
    - assets/animations/
    - assets/images/results/
    - assets/images/
    

# flutter_native_splash config (light + dark)
flutter_native_splash:
  android: true
  ios: true
  web: true

  # Light mode splash
  image: assets/logos/Tesia_Light.png
  color: "#FFFFFF"

  # Dark mode splash
  image_dark: assets/logos/Tesia_Dark.png
  color_dark: "#03132f"

  # Force dark mode splash 
  android_12:
    image: assets/logos/Tesia_Light.png
    color: "#FFFFFF"
    image_dark: assets/logos/Tesia_Dark.png
    color_dark: "#03132f"

  android_gravity: center
  ios_content_mode: center
  fullscreen: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/Tesia_Dark.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logos/Tesia_Dark.png"

dependency_overrides:
  js: ^0.7.2
